### ISSUE TITLE
On first time use of the app, I get an error and Figma Plus fails to integrate with my app on MacOS

### ISSUE THREAD

**Issue by BenFryc** [figma-plus/figma-plus#5]
Here is the error I receive: 

Unhandled Error
Error: EACCES: permission denied, copyfile '/Applications/Figma.app/Contents/Resources/app.asar' -> '/Applications/Figma.app/Contents/Resources/app.asar.bk'
    at Object.fs.copyFileSync (original-fs.js:2026:3)
    at writePacked (/private/var/folders/ql/l876j9rx1xv16s403t15x4f40000gp/T/AppTranslocation/18B27A1C-8DF2-4B53-9BAD-CEDB9E9DAE14/d/Figma Plus.app/Contents/Resources/app.asar/renderer.js:281:18)
    at /private/var/folders/ql/l876j9rx1xv16s403t15x4f40000gp/T/AppTranslocation/18B27A1C-8DF2-4B53-9BAD-CEDB9E9DAE14/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/asar.js:157:18
    at writeFileListToStream (/private/var/folders/ql/l876j9rx1xv16s403t15x4f40000gp/T/AppTranslocation/18B27A1C-8DF2-4B53-9BAD-CEDB9E9DAE14/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:42:10)
    at ReadStream.<anonymous> (/private/var/folders/ql/l876j9rx1xv16s403t15x4f40000gp/T/AppTranslocation/18B27A1C-8DF2-4B53-9BAD-CEDB9E9DAE14/d/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:37:16)

**Comment by jackiecorn** [comment]
Hi Ben, did you have an older version of Figma Plus installed before this release?
If you did, please go to ~/Library/Application Support/ and delete the Figma Plus folder and try again.

**Comment by jackiecorn** [comment]
If it still doesn't work, try this:
1. In Figma Plus, click uninstall, quit Figma Plus.
2. Run Figma app.
3. Quit Figma app.
4. Delete cache files of Figma Plus under “~/Library/Application Support/Figma Plus”.
5. Run Figma Plus, click install.

Let us know what happens. 👍🏼

**Comment by BenFryc** [comment]
> If it still doesn't work, try this:
> 
> 1. In Figma Plus, click uninstall, quit Figma Plus.
> 2. Run Figma app.
> 3. Quit Figma app.
> 4. Delete cache files of Figma Plus under “~/Library/Application Support/Figma Plus”.
> 5. Run Figma Plus, click install.
> 
> Let us know what happens. 👍🏼

This could be user error here, but I'm not seeing Figma Plus in my Application Support directory.

Also for the 2nd suggestion, I dont see a uninstall option in Figma Plus. I see this when I load the app (after the error window I shared the contents above is closed): 
<img width="392" alt="Screenshot 2019-05-07 10 52 43" src="https://user-images.githubusercontent.com/36085485/57309602-60172880-70b6-11e9-8ae5-358a170cd7ea.png">

**Comment by jackiecorn** [comment]
@cdes any ideas?

**Comment by BenFryc** [comment]
When hitting the install button, I see a prompt to Quit Figma, I click quit, and then I see the following error as described above: 
<img width="563" alt="Screenshot 2019-05-07 10 54 20" src="https://user-images.githubusercontent.com/36085485/57309742-96ed3e80-70b6-11e9-86a1-156f5e17cf5d.png">

**Comment by jackiecorn** [comment]
We are still investigating into this issue.
Meanwhile, can you help us to test if this works:
1. Copy and paste you Figma app from the Applications folder onto your Desktop (make sure it's not a shortcut but an actual copy of the app file)
2. Delete the Figma app from Applications folder.
3. Run the Figma Plus installer.
4. If it asks to locate your app, point it to your Figma app on the desktop.
5. Open the Figma app.

Please let us know how this goes, it will help us to identify the problem.

**Comment by cdes** [comment]
Possibly related issue:
https://github.com/jprichardson/node-fs-extra/issues/546

**Comment by BenFryc** [comment]
> We are still investigating into this issue.
> Meanwhile, can you help us to test if this works:
> 
> 1. Copy and paste you Figma app from the Applications folder onto your Desktop (make sure it's not a shortcut but an actual copy of the app file)
> 2. Delete the Figma app from Applications folder.
> 3. Run the Figma Plus installer.
> 4. If it asks to locate your app, point it to your Figma app on the desktop.
> 5. Open the Figma app.
> 
> Please let us know how this goes, it will help us to identify the problem.

This worked! Not sure why, but it worked.
